# Generated by Django 3.0 on 2020-02-13 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название статьи')),
                ('text', models.TextField(verbose_name='Текст статьи')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Дата написания')),
            ],
            options={
                'verbose_name': 'статья',
                'verbose_name_plural': 'статьи',
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(verbose_name='Цифра класса')),
                ('letter', models.CharField(max_length=1, verbose_name='Буква класса')),
            ],
            options={
                'verbose_name': 'школьный класс',
                'verbose_name_plural': 'школьные классы',
            },
        ),
        migrations.CreateModel(
            name='DayOfWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dayname', models.CharField(max_length=50, verbose_name='Имя дня')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director', models.CharField(max_length=50, verbose_name='username директора')),
                ('name', models.CharField(max_length=50, verbose_name='имя школы')),
                ('site', models.URLField(blank=True, verbose_name='Сайт')),
            ],
            options={
                'verbose_name': 'школа',
                'verbose_name_plural': 'школы',
            },
        ),
        migrations.CreateModel(
            name='TimetableSchoolSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sublocalid', models.IntegerField(verbose_name='Порядковый номер урока')),
                ('subjSourceId', models.IntegerField(verbose_name='ID школьного предмета')),
                ('teacher', models.IntegerField(verbose_name='ID учителя')),
                ('timeOfStart', models.TimeField(verbose_name='Время начала')),
                ('timeOfEnd', models.TimeField(verbose_name='Время конца')),
                ('dayofweek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.DayOfWeek')),
            ],
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolClass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Class')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subj_name', models.CharField(max_length=100, verbose_name='Название предмета')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.School')),
            ],
            options={
                'verbose_name': 'школьный предмет',
                'verbose_name_plural': 'школьные предметы',
            },
        ),
        migrations.AddField(
            model_name='dayofweek',
            name='timetable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Timetable'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50, verbose_name='Автор')),
                ('text', models.CharField(max_length=200, verbose_name='Текст')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Article')),
            ],
            options={
                'verbose_name': 'комментарий',
                'verbose_name_plural': 'комментарии',
            },
        ),
        migrations.AddField(
            model_name='class',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.School'),
        ),
        migrations.AddField(
            model_name='article',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.School'),
        ),
    ]
