# Generated by Django 3.0 on 2020-02-02 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='id_sc',
        ),
    ]
